services:
  postgres:
    image: postgres:16-alpine
    container_name: demandflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    volumes:
      - demandflow_postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    container_name: demandflow-localstack
    restart: unless-stopped

    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      DEBUG: "0"

    ports:
      - "4566:4566"
  spark:
    image: apache/spark:3.5.9-scala2.12-java17-python3-r-ubuntu

    profiles:
      - processing

    working_dir: /opt/demandflow

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      LOCALSTACK_INTERNAL_ENDPOINT: ${LOCALSTACK_INTERNAL_ENDPOINT}
      PYSPARK_PYTHON: python3

    depends_on:
      - localstack

    volumes:
      - ./src:/opt/demandflow/src:ro

    mem_limit: 3g
    cpus: "2.0"

volumes:
  demandflow_postgres_data:
  
